%
%Code generated by AMIGO to compute constraints for OED and PE
%
	Cit_mrna   =privstruct.yteor(end,1);
	Cit_foldedP=privstruct.yteor(end,2);
	Cit_fluo   =privstruct.yteor(end,3);
	cviol      =privstruct.yteor(end,4);
switch iexp
case 1
case 2
	IPTG=inputs.exps.u{2};end

% Definition of constraints
	h(1) =0;
switch iexp
case 1

% End-point inequality constraints for experiment 1
	hh{iexp}(1,1) = cviol;
case 2
end
